### ISSUE TITLE
Trackpoint stops working after updating from Kernel 5.4.11 to 5.4.12

### ISSUE THREAD

**Issue by bejuba** [Lunm0us/linux-tp1gen3#2]
Hi,

first of all thank you for making my function keys work they it should!  :)
Unfortunately in recent kernel versions a [commit](
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.4.18&id=4091fbf6cc143c8ccd8275eaa642b2f2afe7c4ab) broke the functionality of the trackpoint. The bug is filed [here](https://bugzilla.kernel.org/show_bug.cgi?id=206271) and a workaround that requires the compilation of the kernel is discussed [here](https://forum.manjaro.org/t/trackpoint-stops-working-after-updating-from-kernel-5-4-11-to-5-4-12/120438).
This stuff is way above my level of knowledge so i am asking for help here. Specifically i am wondering if it is possible to modify the patches here to include the workaround without the need of recompiling the whole kernel after an update or ideally to provide the missing mappings and work on an upstream fix.

**Comment by Lunm0us** [comment]
The file modified in the commit is compiled into the hid module which Arch Linux actually configures as a module. So in theory it would be possible to patch it and build it out of tree. However the hid module is, as far as I can see, not only responsible for the touchpad but nearly everything input related. Furthermore we'd need to replace the original hid module shipped with the kernel. 

I'll try to work on the workaround in the next couple of days but it probably won't apply as nice as the keyboard module. For everything else we'd need to pin down the bug.

P.s. thanks for the links

**Comment by Lunm0us** [comment]
Think I found the bug. I pushed a patched version (actually for the touchpad; not the hid module) to the [multitouch-hid branch](https://github.com/Lunm0us/linux-tp1gen3/tree/hid-multitouch). Could you check if it works on your device?

```bash
cd hid-multitouch
make
sudo make run
```
should load the patched module and give you 20 seconds to check. After that it should revert to the upstream module automatically.

**Comment by bejuba** [comment]
Than you so much for looking into this. It works flawlessly!

**Comment by Lunm0us** [comment]
The commit contains a dkms module with the fix. However the blacklisting part is still a bit flaky. Let me know if it works.

**Comment by bejuba** [comment]
I can confirm that the new dkms module also fixes the trackpoint :) Thanks again!

**Comment by gebim** [comment]
I'm on an X1 gen1 with kernel 5.4 (ubuntu 20.04) and also affected by the non-working Trackpoint.

I  have a question an request:

*) Reattaching the keyboard solved the issue and a simple  "libinput list-devices" lists the trackpoint and is working well. 
Is there a way to trigger this in SW ? Let's a say by a script after login ?
https://bugs.launchpad.net/ubuntu/+source/libinput/+bug/1878882

*) As a novice end-user, it would be very much welcomed if somebody could give me a bit more detailed info, how to build the dkms hid-multitouch kernel module ?
