### ISSUE TITLE
Add instructions for Ubuntu

### ISSUE THREAD

**Issue by bitbacchus** [Lunm0us/linux-tp1gen3#4]
Thanks so much for providing this repo! It just saved my day and my X1 Tablet is now up and running.

I use Ubuntu and it took me a bit to 'translate' your instructions. Therefore I wrote them down. Please feel free to add them to your Readme.md

Best,
Sebastian

### Ubuntu installation (DKMS)

1. download and extract `linux-tp1gen3-master` 

```
cd linux-tp1gen3-master
```

   

2. edit `./hid/src/dkms.conf`
   Replace the placeholders **@_PKGBASE@** and **@VERSION@** with the actual values being hid-lenovo-tp1gen3 and the current version (e.g. 0.2.0). The version can be determined from the PKBUILD file.

3. install the DKMS package

```{.sh}
sudo apt-get install build-essential dkms 
```

4. copy files

```{.sh}
sudo mkdir -p /usr/src/hid-lenovo-tp1gen3-<version>
sudo cp -a ./hid/src/* /usr/src/hid-lenovo-tp1gen3-<version> 
```

5. build and install

```{.sh}
sudo dkms add -m hid-lenovo-tp1gen3 -v <version>
sudo dkms build -m hid-lenovo-tp1gen3 -v <version>
sudo dkms install -m hid-lenovo-tp1gen3 -v <version>
```

Check if the module was successfully added to dkms

```{.sh}
~$ dkms status
hid-lenovo-tp1gen3, 0.2.0, 5.6.14, x86_64: installed
```

6. blacklist the old module
   Add `blacklist hid-multitouch` to the file `/etc/modprobe.d/blacklist.conf`
   Then reboot.

**Comment by bitbacchus** [comment]
Oh, and btw. the ACPI stuff also works with BIOS 1.36

**Comment by Lunm0us** [comment]
Thank you very much for writing down nice and readable instructions, I really appreciate it. I'll add them to the readme with the next commit.
